name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Package and upload chart
        shell: bash
        env:
          REGISTRY: "ghcr.io"
          REPOSITORY: "${{ github.repository }}"
          TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          USER: "${{ github.repository_owner }}"
        run: |
          rm -rf dist
          mkdir dist
          find ./charts -mindepth 1 -maxdepth 1 -type d -exec helm package {} -d dist/ \;
          echo "${TOKEN}" | helm registry login "${REGISTRY}/${REPOSITORY,,}" -u "${USER}" --password-stdin
          for file in dist/*; do
            helm push "$file" "oci://${REGISTRY}/${REPOSITORY,,}/charts"
          done
