apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "butane-oracle.fullname" . }}
  labels:
    {{- include "butane-oracle.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if .Values.logs }}
    {{- with .Values.logs }}
    logs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- else }}
    logs:
      json: true
      level: info
    {{- end }}
    {{- with .Values.keygen }}
    keygen:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    sundaeswap:
      kupo_address: {{ .Values.kupo.url }}
    minswap:
      kupo_address: {{ .Values.kupo.url }}
    spectrum:
      kupo_address: {{ .Values.kupo.url }}
    # This is the address of your current FROST public key. The key generation process will print it.
    frost_address: {{ .Values.frost.address }}
    # Every node must agree on this.
    {{- with .Values.peers }}
    peers:
      {{- toYaml . | nindent 6 }}
    {{- end }}
