apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "butane-oracle.fullname" . }}
  labels:
    {{- include "butane-oracle.labels" . | nindent 4 }}
data:
  config.yaml: |
    api_port: 8080      # Port to serve API requests
    network_port: 31415 # Port to handle traffic from other nodes
    health_port: 18000  # Port to report our health status
    heartbeat_ms: 500   # How long should the leader wait before sending a heartbeat
    timeout_ms: 2000     # How long should we wait before picking a new leader
    consensus: true
    {{- if .Values.logs }}
    {{- with .Values.logs }}
    logs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- else }}
    logs:
      json: true
      level: info
    {{- end }}
    {{- with .Values.keygen }}
    keygen:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    synthetics:
      - name: USDb
        price: 1
        digits: 6
        collateral:
          - ADA
          - BTN
          - ENCS
          - LENFI
          - MIN
          - SNEK
      - name: USDs
        price: 1
        digits: 6
        collateral:
          - ADA
          - BTN
          - DJED
          - USDb
          - iUSD
          - myUSD
      - name: EURb
        price: 1.0931
        digits: 6
        collateral:
          - ADA
          - USDb
          - USDs
          - BTN
      - name: JPYb
        price: 0.006900120752113162
        digits: 6
        collateral:
          - ADA
          - USDb
          - USDs
          - BTN
      - name: BTCb
        price: 45944.3
        digits: 8
        collateral:
          - ADA
          - USDb
          - USDs
          - BTN
          - ENCS
          - LENFI
          - MIN
          - SNEK
      - name: MATICb
        price: 0.8206
        digits: 6
        collateral:
          - ADA
          - BTCb
          - BTN
          - ENCS
          - LENFI
          - MIN
          - SNEK
      - name: SOLp
        price: 0.010185788787483703
        digits: 9
        collateral:
          - ADA
          - USDb
          - USDs
          - BTN
          - ENCS
          - LENFI
          - MIN
          - SNEK
    collateral:
      - name: ADA
        price: 0.5235
        digits: 6
      - name: BTCb
        price: 45944.3
        digits: 8
      - name: BTN
        asset_id: 016be5325fd988fea98ad422fcfd53e5352cacfced5c106a932a35a4.42544e
        price: 1.001
        digits: 6
      - name: DJED
        asset_id: 8db269c3ec630e06ae29f74bc39edd1f87c819f1056206e879a1cd61.446a65644d6963726f555344
        price: 1
        digits: 6
      - name: ENCS
        asset_id: 9abf0afd2f236a19f2842d502d0450cbcd9c79f123a9708f96fd9b96.454e4353
        price: 0.5923
        digits: 6
      - name: iUSD
        asset_id: f66d78b4a3cb3d37afa0ec36461e51ecbde00f26c8f0a68f94b69880.69555344
        price: 0.79
        digits: 6
      - name: LENFI
        asset_id: 8fef2d34078659493ce161a6c7fba4b56afefa8535296a5743f69587.41414441
        price: 3.79
        digits: 6
      - name: MIN
        asset_id: 29d222ce763455e3d7a09a665ce554f00ac89d2e99a1a83d267170c6.4d494e
        price: 0.03457
        digits: 6
      - name: myUSD
        asset_id: 92776616f1f32c65a173392e4410a3d8c39dcf6ef768c73af164779c.4d79555344
        price: 1
        digits: 6
      - name: SNEK
        asset_id: 279c909f348e533da5808898f87f9a14bb2c3dfbbacccd631d927a3f.534e454b
        price: 0.001194
        digits: 0
      - name: USDb
        price: 1
        digits: 6
      - name: USDs
        price: 1
        digits: 6
    bybit:
      tokens:
        - token: ADA
          unit: USD
          stream: ADAUSDT
        - token: BTCb
          unit: USD
          stream: BTCUSDT
        - token: MATICb
          unit: USD
          stream: MATICUSDT
        - token: SOLp
          unit: USD
          stream: SOLUSDT
    sundaeswap:
      use_api: false
      kupo_address: {{ .Values.kupo.url }}
      credential: e0302560ced2fdcbfcb2602697df970cd0d6a38f94b32703f51c312b/*
      policy_id: e0302560ced2fdcbfcb2602697df970cd0d6a38f94b32703f51c312b
      pools:
        - token: BTN
          unit: ADA
          asset_id: e0302560ced2fdcbfcb2602697df970cd0d6a38f94b32703f51c312b.000de1408e76c60dd3cbccdf8af264e560686078f05345d96d90c4af19c6c4f6
        - token: ENCS
          unit: ADA
          asset_id: e0302560ced2fdcbfcb2602697df970cd0d6a38f94b32703f51c312b.000de1403d59c9a766909da1c3cda90e73a9582025b17d7eb0be44cbd8b2dadd
        - token: iUSD
          unit: ADA
          asset_id: e0302560ced2fdcbfcb2602697df970cd0d6a38f94b32703f51c312b.000de140c7ef237f227542a0c8930d37911491c56a341fdef8437e0f21d024f8
        - token: SNEK
          unit: ADA
          asset_id: e0302560ced2fdcbfcb2602697df970cd0d6a38f94b32703f51c312b.000de140cacb7fd5f5b84bf876d40dc60d4991c72112d78d76132b1fb769e6ad
      max_concurrency: 3
      retries: 3
    minswap:
      kupo_address: {{ .Values.kupo.url }}
      credential: e1317b152faac13426e6a83e06ff88a4d62cce3c1634ab0a5ec13309/*
      pools:
        - token: BTN
          unit: ADA
          asset_id: 0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1.35b025a78482d2662e3b44fb8321996c6533faa48fb0f3fd81b11a034978e1e8
        - token: DJED
          unit: ADA
          asset_id: 0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1.d944eda9d4fd8c26171a4362539bfd4ccf35f5a4d0cc7525b22327b997a4f4b9
        - token: ENCS
          unit: ADA
          asset_id: 0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1.2324756b8e7e74da8feb879e2f053789363d045e554eaa17d365d1b52f4a9f8c
        - token: iUSD
          unit: ADA
          asset_id: 0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1.8fde43a3f0b9f0e6f63bec7335e0b855c6b62a4dc51f1b762ccb6dfbbafcfe47
        - token: LENFI
          unit: ADA
          asset_id: 0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1.39b9b709ac8605fc82116a2efc308181ba297c11950f0f350001e28f0e50868b
        - token: MIN
          unit: ADA
          asset_id: 0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1.6aa2153e1ae896a95539c9d62f76cedcdabdcdf144e564b8955f609d660cf6a2
        - token: myUSD
          unit: ADA
          asset_id: 0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1.1aa8961f4c11d8cebb43c8306a1ecdbebf0103ae2d30bf31b3676445a954ae05
        - token: SNEK
          unit: ADA
          asset_id: 0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1.63f2cbfa5bf8b68828839a2575c8c70f14a32f50ebbfa7c654043269793be896
      max_concurrency: 3
      retries: 3
    spectrum:
      kupo_address: {{ .Values.kupo.url }}
      credential: 6b9c456aa650cb808a9ab54326e039d5235ed69f069c9664a8fe5b69/*
      pools:
        - token: BTN
          unit: ADA
          asset_id: e8afc6fe1f4f3bef280bed8a9e3ba68dbc19c8dfade05d800c8bd3ed.42544e5f4144415f4e4654
        - token: ENCS
          unit: ADA
          asset_id: a209432e4f3aa5136521daa5c2be9bb12f52e3356359843620e26ea6.454e43535f4144415f4e4654
        - token: iUSD
          unit: ADA
          asset_id: 16152a3a0c838c07086d1dd188c7f7846ebd418a2af1b80a5d0c3032.695553445f4144415f4e4654
        - token: LENFI
          unit: ADA
          asset_id: 2b12a80b6dae4b251faa611946efb05a33ca54920ba50cb220eb7d8b.414144415f4144415f4e4654
        - token: MIN
          unit: ADA
          asset_id: dd6a3921cc3716f65abc66ad0897f142dd6dbee80c642196e9bf3d86.4d494e5f4144415f4e4654
        - token: SNEK
          unit: ADA
          asset_id: f8fd67ee46f66da669f68dc941090eb753687636b47fc6fd7f5e6254.534e454b5f4144415f4e4654
      max_concurrency: 3
      retries: 3
    frost_address: {{ .Values.frost.address }}
      # This is the address of your current FROST public key. The key generation process will print it.
    # Every node must agree on this.
    {{- with .Values.peers }}
    peers:
      {{- toYaml . | nindent 6 }}
    {{- end }}
