apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "butane-oracle.fullname" . }}
  labels:
    {{- include "butane-oracle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "butane-oracle.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "butane-oracle.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "butane-oracle.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          {{- if .Values.maintenance | default false }}
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "sleep infinity" ]
          {{- else }}
          command: ["./oracles", "-c", "/app/config.yaml"]
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KEYS_DIRECTORY
              value: "/app/keys"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: pem-secret-key
              mountPath: /app/keys/private.pem
              subPath: private.pem
            - name: frost-secret-key
              mountPath: {{ tpl .Values.frost.frostSKeyFilePath . }}
              subPath: frost.skey
            - name: frost-secret-key
              mountPath: {{ tpl .Values.frost.frostVKeyFilePath . }}
              subPath: frost.vkey
      volumes:
          - name: pem-secret-key
            secret:
              secretName: {{ .Values.secretName }}
          - name: frost-secret-key
            secret:
              secretName: {{ .Values.secretName }}
          - name: config
            configMap:
              name: {{ include "butane-oracle.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
